In [33]:
import re
import json
import math
import time
import tempfile
import subprocess
from pathlib import Path

import os
os.add_dll_directory("C:/msys64/ucrt64/bin")
import cppbloom as bloom

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.sparse as sp

from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.base import BaseEstimator, TransformerMixin
from scipy.sparse import csr_matrix
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, precision_recall_curve, classification_report, confusion_matrix
import joblib

In [34]:
PROJECT_DIR = Path(".")
DATA_PATH = PROJECT_DIR / "data" / "urldata.csv"

TARGET_FPR = 0.05
N_REPEATS = 8
N_FEATURES = 2**13
RANDOM_STATE = 42

In [35]:
def run_baseline_once() -> dict:
    eval = bloom.Evaluator()
    res = eval.run_single_experiment(460000,TARGET_FPR,"data/real.txt","data/fake.txt")

    result = {}

    result["time_ms"] = res.timeTakenInNs / 1000000.0
    result["fp_count"] = res.falsePositive
    result["insert_count"] = res.insertCount
    result["negative_queries"] = res.negativeQueryCount
    result["memory_mb"] = res.memoryNeeded / (1024*1024)
    result["time_per_query_ns"] = res.timeTakenInNs / (res.negativeQueryCount+res.insertCount)
    result["throughtput_s"] = (res.insertCount+res.negativeQueryCount) / (res.timeTakenInNs / 1000000000)

    result["observed_fpr"] = result["fp_count"] / max(1, result["negative_queries"])
    return result

In [36]:
baseline_rows = []
for i in range(N_REPEATS):
    row = run_baseline_once()
    row["trial"] = i + 1
    baseline_rows.append(row)

baseline_df = pd.DataFrame(baseline_rows)

summary = baseline_df.agg({
    "time_ms": ["mean", "std"],
    "throughtput_s" : ["mean", "std"],
    "memory_mb": ["mean", "std"],
    "time_per_query_ns": ["mean", "std"],
    "observed_fpr": ["mean", "std"],
    "fp_count": ["mean", "std"],
    "insert_count": ["mean", "std"],
    "negative_queries": ["mean", "std"],
})

display(baseline_df)
display(summary)
summary.to_csv(f"results/baseline_{TARGET_FPR}_{N_FEATURES}.csv")

,time_ms,fp_count,insert_count,negative_queries,memory_mb,time_per_query_ns,throughtput_s,observed_fpr,trial
0,34.2772,1575,344928,75536,0.341919,81.522318,1.226658e+07,0.020851,1
1,34.7734,1575,344928,75536,0.341919,82.702443,1.209154e+07,0.020851,2
2,33.7378,1575,344928,75536,0.341919,80.239450,1.246270e+07,0.020851,3
3,34.3010,1575,344928,75536,0.341919,81.578922,1.225807e+07,0.020851,4
4,33.2189,1575,344928,75536,0.341919,79.005337,1.265737e+07,0.020851,5
5,36.2429,1575,344928,75536,0.341919,86.197391,1.160128e+07,0.020851,6
6,32.7509,1575,344928,75536,0.341919,77.892281,1.283824e+07,0.020851,7
7,34.9632,1575,344928,75536,0.341919,83.153849,1.202590e+07,0.020851,8

,time_ms,throughtput_s,memory_mb,time_per_query_ns,observed_fpr,fp_count,insert_count,negative_queries
mean,34.283163,1.227521e+07,0.341919,81.536499,0.020851,1575.0,344928.0,75536.0
std,1.090322,3.870485e+05,0.000000,2.593140,0.000000,0.0,0.0,0.0

In [37]:
with open("data/real.txt", "r", encoding="utf-8") as f:
    real_urls = [line.strip() for line in f if line.strip()]

with open("data/fake.txt", "r", encoding="utf-8") as f:
    fake_urls = [line.strip() for line in f if line.strip()]

real_df = pd.DataFrame({
    "url": real_urls,
    "y": 1
})

fake_df = pd.DataFrame({
    "url": fake_urls,
    "y": 0
})

df = pd.concat([real_df, fake_df], ignore_index=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

df.to_csv("data/labeled_url.csv", index=False)

print(df.head())
print(df["y"].value_counts())

                                                 url  y
0                                   blackcomedy.net/  1
1  nydailynews.com/blogs/rangers/2011/01/rangers-...  1
2                  welections.wordpress.com/2010/12/  1
3                  italianlanguagecourseschools.com/  1
4  autodealerbase.com/dealers-12A040FD/Joe-Bowman...  1
y
1    344928
0     75536
Name: count, dtype: int64

In [38]:
df_good = df[df["y"] == 1].copy()
df_bad = df[df["y"] == 0].copy()

bad_train, bad_test = train_test_split(
    df_bad,
    test_size=0.2,
    random_state=42
)

train_df = pd.concat([df_good, bad_train]).sample(frac=1, random_state=42).reset_index(drop=True)

test_df = pd.concat([df_good, bad_test]).sample(frac=1, random_state=42).reset_index(drop=True)

X_train = train_df["url"].astype(str).str.strip().values
y_train = train_df["y"].values

X_test = test_df["url"].astype(str).str.strip().values
y_test = test_df["y"].values

### **Model**

In [39]:
def fast_sparse_vectorizer(X, num_bins=16384):
    strings = X.tolist() if isinstance(X, (pd.Series, np.ndarray)) else list(X)
    
    data, indices, indptr = bloom.extract_sparse_ngrams(strings, num_bins)
    sparse_matrix = sp.csr_matrix((data, indices, indptr), shape=(len(strings), num_bins))
    
    return sparse_matrix

pipeline_vectorizer = FunctionTransformer(
    fast_sparse_vectorizer, 
    kw_args={"num_bins": N_FEATURES}
)

model = Pipeline(steps=[
    ("hash", pipeline_vectorizer),
    ("clf", SGDClassifier(
        loss="log_loss",
        alpha=1e-6,
        max_iter=200,
        tol=1e-3,
        random_state=42
    ))
])

In [40]:
model.fit(X_train,y_train)

Pipeline(steps=[('hash',
                 FunctionTransformer(func=<function fast_sparse_vectorizer at 0x000001E610EE0F40>,
                                     kw_args={'num_bins': 8192})),
                ('clf',
                 SGDClassifier(alpha=1e-06, loss='log_loss', max_iter=200,
                               random_state=42))])

In [41]:
urls = X_test

start = time.perf_counter_ns()
X_features = model.named_steps["hash"].transform(urls)
end = time.perf_counter_ns()

feature_time = end - start

start = time.perf_counter_ns()
probs = model.named_steps["clf"].predict_proba(X_features)
end = time.perf_counter_ns()

clf_time = end - start

print(f"Feature extraction: {feature_time/1e6:.3f} ms")
print(f"Classifier:         {clf_time/1e6:.3f} ms")
print(f"Total:              {(feature_time+clf_time)/1e6:.3f} ms")

Feature extraction: 190.917 ms
Classifier:         37.719 ms
Total:              228.636 ms

In [42]:
y_pred = model.predict(X_test)
y_score = model.predict_proba(X_test)[:, 1]

print("AUC:", roc_auc_score(y_test, y_score))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

AUC: 0.985640313583311
Confusion matrix:
 [[ 12792   2316]
 [  2958 341970]]
              precision    recall  f1-score   support

           0     0.8122    0.8467    0.8291     15108
           1     0.9933    0.9914    0.9923    344928

    accuracy                         0.9854    360036
   macro avg     0.9027    0.9191    0.9107    360036
weighted avg     0.9857    0.9854    0.9855    360036

In [43]:
def model_size_mb(trained_model) -> float:
    with tempfile.NamedTemporaryFile(suffix=".joblib", delete=False) as f:
        tmp = Path(f.name)
    joblib.dump(trained_model, tmp)
    size_mb = tmp.stat().st_size / (1024 * 1024)
    tmp.unlink(missing_ok=True)
    return size_mb

def run_ml_metrics_once(trained_model, X_eval, y_eval, threshold=0.5):
    t0 = time.perf_counter()
    scores = trained_model.predict_proba(X_eval)[:, 1]
    preds = (scores >= threshold).astype(int)
    t1 = time.perf_counter()

    tn, fp, fn, tp = confusion_matrix(y_eval, preds, labels=[0, 1]).ravel()

    negative_queries = int((y_eval == 0).sum())
    observed_fpr = fp / max(1, negative_queries)

    result = {
        "time_taken_ms": (t1 - t0) * 1000.0,
        "fp_count": int(fp),
        "negative_queries": int(negative_queries),
        "observed_fpr": float(observed_fpr),
        "true_positive": int(tp),
        "true_negative": int(tn),
        "false_negative": int(fn),
        "insert_count_analog": int((y_eval == 1).sum()),  
        "memory_needed_mb": model_size_mb(trained_model),
    }
    return result

ml_res = run_ml_metrics_once(model, X_test, y_test, threshold=0.5)
print(ml_res)

{'time_taken_ms': 293.9206000883132, 'fp_count': 2316, 'negative_queries': 15108, 'observed_fpr': 0.15329626687847497, 'true_positive': 341970, 'true_negative': 12792, 'false_negative': 2958, 'insert_count_analog': 344928, 'memory_needed_mb': 0.032662391662597656}

In [44]:
print(f"Time taken: {ml_res['time_taken_ms']:.2f}ms")
print(f"FP: {ml_res['fp_count']}")
print(f"Total inserts: {ml_res['insert_count_analog']}")
print(f"Negative Queries: {ml_res['negative_queries']}")
print(f"Memory needed: {ml_res['memory_needed_mb']:.6f} MB")
print(f"Observed FP rate: {ml_res['observed_fpr']:.6f}")

Time taken: 293.92ms
FP: 2316
Total inserts: 344928
Negative Queries: 15108
Memory needed: 0.032662 MB
Observed FP rate: 0.153296

In [45]:
def evaluate_learned_bloom_with_backup(
    model, 
    df,
    path_real="data/real.txt", 
    path_fake="data/fake.txt",
    threshold_grid=None, 
    target_fpr=0.01, 
    output_csv="lbf_threshold_metrics.csv"
):
    if threshold_grid is None:
        threshold_grid = np.linspace(0.05, 0.95, 37)

    positive_urls = df.loc[df["y"] == 1, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)
    negative_urls = df.loc[df["y"] == 0, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)

    clf = model.named_steps["clf"]
    weights = clf.coef_[0].tolist()
    bias = float(clf.intercept_[0])
    num_bins = model.named_steps["hash"].kw_args["num_bins"]

    pos_scores = model.predict_proba(positive_urls)[:, 1]
    neg_scores = model.predict_proba(negative_urls)[:, 1]

    candidates = []

    for t in threshold_grid:
        pos_pred_model = pos_scores >= t
        neg_pred_model = neg_scores >= t

        model_fp_rate = float(neg_pred_model.mean())

        if model_fp_rate >= target_fpr:
            backup_fpr_target = 1e-9
        else:
            backup_fpr_target = (target_fpr - model_fp_rate) / max(1e-12, (1.0 - model_fp_rate))
            backup_fpr_target = min(max(backup_fpr_target, 1e-9), 0.99)

        rejected_pos_mask = ~pos_pred_model
        backup_size = int(rejected_pos_mask.sum())

        evaluator = bloom.Evaluator()
        res = evaluator.run_learned_experiment(
            weights,                   
            bias,                         
            float(t),                        
            num_bins,                  
            max(1, int(backup_size)),     
            backup_fpr_target,                
            path_real,                         
            path_fake
        )

        total_time_ms = res.timeTakenInNs / 1_000_000.0
        throughput = (res.insertCount + res.negativeQueryCount) / (res.timeTakenInNs / 1_000_000_000.0)

        candidates.append({
            "threshold": float(t),
            "model_fp_rate": model_fp_rate,
            "backup_target_fpr": backup_fpr_target,
            "time_taken_ms": total_time_ms,
            "time_per_query_ns": res.timeTakenInNs / max(1, (res.insertCount + res.negativeQueryCount)), 
            "throughput_s": int(throughput),
            "insert_count": res.insertCount,
            "negative_queries": res.negativeQueryCount,
            "false_negative": res.falseNegative,
            "false_positive": res.falsePositive,
            "observed_fpr": res.falsePositive / max(1, res.negativeQueryCount),
            "total_memory_mb": res.memoryNeeded / (1024 * 1024.0),
            "backup_key_count": backup_size,
        })

    result_df = pd.DataFrame(candidates)
    result_df.to_csv(output_csv, index=False)
    print(f"Successfully evaluated {len(threshold_grid)} thresholds via C++. Results saved to '{output_csv}'.")

    best_df = result_df.sort_values(
        by=["observed_fpr", "total_memory_mb", "time_taken_ms"]
    ).reset_index(drop=True)

    best = best_df.iloc[0].to_dict()
    return best, result_df

In [46]:
best_lbf, result_df = evaluate_learned_bloom_with_backup(
    model=model,
    df=df,
    target_fpr=TARGET_FPR,
    output_csv=f"results/result_{TARGET_FPR}_{N_FEATURES}.csv"
)

Successfully evaluated 37 thresholds via C++. Results saved to 'results/result_0.05_8192.csv'.

In [47]:
result_df

,threshold,model_fp_rate,backup_target_fpr,time_taken_ms,time_per_query_ns,throughput_s,insert_count,negative_queries,false_negative,false_positive,observed_fpr,total_memory_mb,backup_key_count
0,0.050,0.316953,1.000000e-09,145.7379,346.612076,2885069,344928,75536,0,23629,0.312818,0.064110,310
1,0.075,0.288929,1.000000e-09,179.9255,427.921296,2336878,344928,75536,0,21495,0.284566,0.064606,406
2,0.100,0.267584,1.000000e-09,128.7398,306.185072,3265998,344928,75536,0,19867,0.263014,0.065216,525
3,0.125,0.251726,1.000000e-09,132.8417,315.940723,3165150,344928,75536,0,18641,0.246783,0.065857,649
4,0.150,0.238702,1.000000e-09,130.0473,309.294732,3233162,344928,75536,0,17651,0.233677,0.066429,760
5,0.175,0.228150,1.000000e-09,149.3877,355.292486,2814582,344928,75536,0,16843,0.222980,0.067039,879
6,0.200,0.218186,1.000000e-09,139.4398,331.633148,3015380,344928,75536,0,16091,0.213024,0.067726,1013
7,0.225,0.208764,1.000000e-09,130.3808,310.087903,3224892,344928,75536,0,15375,0.203545,0.068451,1154
8,0.250,0.200142,1.000000e-09,130.8248,311.143879,3213947,344928,75536,0,14724,0.194927,0.069176,1295
9,0.275,0.192891,1.000000e-09,137.2922,326.525458,3062548,344928,75536,0,14181,0.187738,0.069839,1423
10,0.300,0.185685,1.000000e-09,136.9067,325.608613,3071171,344928,75536,0,13640,0.180576,0.070457,1544
11,0.325,0.178721,1.000000e-09,146.5279,348.490953,2869514,344928,75536,0,13108,0.173533,0.071144,1678
12,0.350,0.172209,1.000000e-09,127.5143,303.270435,3297387,344928,75536,0,12613,0.166980,0.071983,1841
13,0.375,0.165983,1.000000e-09,161.8071,384.829855,2598550,344928,75536,0,12143,0.160758,0.072769,1993
14,0.400,0.160466,1.000000e-09,125.1586,297.667815,3359449,344928,75536,0,11728,0.155264,0.073723,2179
15,0.425,0.154828,1.000000e-09,136.2378,324.017752,3086250,344928,75536,0,11294,0.149518,0.074661,2361
16,0.450,0.149070,1.000000e-09,142.9873,340.070256,2940568,344928,75536,0,10870,0.143905,0.075607,2546
17,0.475,0.144005,1.000000e-09,129.6821,308.426167,3242267,344928,75536,0,10495,0.138940,0.076691,2756
18,0.500,0.138337,1.000000e-09,124.0395,295.006231,3389758,344928,75536,0,10074,0.133367,0.077721,2957
19,0.525,0.133227,1.000000e-09,137.0899,326.044322,3067067,344928,75536,0,9689,0.128270,0.078934,3193
20,0.550,0.128524,1.000000e-09,138.8314,330.186175,3028594,344928,75536,0,9347,0.123742,0.080261,3450
21,0.575,0.124031,1.000000e-09,141.3573,336.193586,2974476,344928,75536,0,9006,0.119228,0.081734,3737
22,0.600,0.119479,1.000000e-09,141.4154,336.331767,2973254,344928,75536,0,8684,0.114965,0.083420,4065
23,0.625,0.115107,1.000000e-09,134.7345,320.442416,3120685,344928,75536,0,8352,0.110570,0.085182,4407
24,0.650,0.110962,1.000000e-09,137.7993,327.731506,3051278,344928,75536,0,8044,0.106492,0.087029,4767
25,0.675,0.106259,1.000000e-09,147.6071,351.057641,2848535,344928,75536,0,7700,0.101938,0.089264,5202
26,0.700,0.101495,1.000000e-09,149.8019,356.277589,2806800,344928,75536,0,7347,0.097265,0.091675,5670
27,0.725,0.096973,1.000000e-09,137.9330,328.049488,3048320,344928,75536,0,7011,0.092817,0.094460,6212
28,0.750,0.092089,1.000000e-09,156.0774,371.202766,2693945,344928,75536,0,6656,0.088117,0.097725,6847
29,0.775,0.086919,1.000000e-09,133.8590,318.360193,3141096,344928,75536,0,6280,0.083139,0.101440,7570
30,0.800,0.081567,1.000000e-09,149.8991,356.508762,2804980,344928,75536,0,5882,0.077870,0.105873,8431
31,0.825,0.076171,1.000000e-09,138.3832,329.120210,3038403,344928,75536,0,5473,0.072456,0.111214,9470
32,0.850,0.070518,1.000000e-09,163.2599,388.285085,2575427,344928,75536,0,5047,0.066816,0.117630,10718
33,0.875,0.064307,1.000000e-09,156.5453,372.315585,2685893,344928,75536,0,4595,0.060832,0.125984,12343
34,0.900,0.057433,1.000000e-09,127.8911,304.166587,3287672,344928,75536,0,4089,0.054133,0.137253,14534
35,0.925,0.049896,1.094752e-04,140.0021,332.970480,3003269,344928,75536,0,3580,0.047395,0.102409,17629
36,0.950,0.041786,8.572193e-03,135.7619,322.885907,3097069,344928,75536,0,3544,0.046918,0.089417,22775

In [48]:
best_lbf

{'threshold': 0.95,
 'model_fp_rate': 0.04178600500467304,
 'backup_target_fpr': 0.008572192681622251,
 'time_taken_ms': 135.7619,
 'time_per_query_ns': 322.88590699798317,
 'throughput_s': 3097069.0,
 'insert_count': 344928.0,
 'negative_queries': 75536.0,
 'false_negative': 0.0,
 'false_positive': 3544.0,
 'observed_fpr': 0.04691802584198263,
 'total_memory_mb': 0.08941650390625,
 'backup_key_count': 22775.0}