In [131]:
import re
import json
import math
import time
import tempfile
import subprocess
from pathlib import Path

import os
os.add_dll_directory("C:/msys64/ucrt64/bin")
import cppbloom as bloom

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.sparse as sp

from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.base import BaseEstimator, TransformerMixin
from scipy.sparse import csr_matrix
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, precision_recall_curve, classification_report, confusion_matrix
import joblib

In [132]:
PROJECT_DIR = Path(".")
DATA_PATH = PROJECT_DIR / "data" / "urldata.csv"

TARGET_FPR = 0.05
N_REPEATS = 8
N_FEATURES = 2**14
RANDOM_STATE = 42

In [133]:
def run_baseline_once() -> dict:
    eval = bloom.Evaluator()
    res = eval.run_single_experiment(400000,TARGET_FPR,"data/real.txt","data/fake.txt")

    result = {}

    result["time_ms"] = res.timeTakenInNs / 1000000.0
    result["fp_count"] = res.falsePositive
    result["insert_count"] = res.insertCount
    result["negative_queries"] = res.negativeQueryCount
    result["memory_mb"] = res.memoryNeeded / (1024*1024)
    result["time_per_query_ns"] = res.timeTakenInNs / (res.negativeQueryCount+res.insertCount)
    result["throughtput_s"] = (res.insertCount+res.negativeQueryCount) / (res.timeTakenInNs / 1000000000)

    result["observed_fpr"] = result["fp_count"] / max(1, result["negative_queries"])
    return result

In [134]:
baseline_rows = []
for i in range(N_REPEATS):
    row = run_baseline_once()
    row["trial"] = i + 1
    baseline_rows.append(row)

baseline_df = pd.DataFrame(baseline_rows)

summary = baseline_df.agg({
    "time_ms": ["mean", "std"],
    "throughtput_s" : ["mean", "std"],
    "memory_mb": ["mean", "std"],
    "time_per_query_ns": ["mean", "std"],
    "observed_fpr": ["mean", "std"],
    "fp_count": ["mean", "std"],
    "insert_count": ["mean", "std"],
    "negative_queries": ["mean", "std"],
})
display(baseline_df)
display(summary)

,time_ms,fp_count,insert_count,negative_queries,memory_mb,time_per_query_ns,throughtput_s,observed_fpr,trial
0,31.3229,2560,344928,75536,0.297325,74.496033,1.342353e+07,0.033891,1
1,36.7188,2560,344928,75536,0.297325,87.329236,1.145092e+07,0.033891,2
2,35.8017,2560,344928,75536,0.297325,85.148075,1.174425e+07,0.033891,3
3,32.6318,2560,344928,75536,0.297325,77.609022,1.288510e+07,0.033891,4
4,32.8840,2560,344928,75536,0.297325,78.208836,1.278628e+07,0.033891,5
5,32.7767,2560,344928,75536,0.297325,77.953642,1.282814e+07,0.033891,6
6,35.8208,2560,344928,75536,0.297325,85.193501,1.173798e+07,0.033891,7
7,39.9770,2560,344928,75536,0.297325,95.078294,1.051765e+07,0.033891,8

,time_ms,throughtput_s,memory_mb,time_per_query_ns,observed_fpr,fp_count,insert_count,negative_queries
mean,34.741712,1.217173e+07,0.297325,82.627080,0.033891,2560.0,344928.0,75536.0
std,2.855008,9.644305e+05,0.000000,6.790137,0.000000,0.0,0.0,0.0

In [135]:
df = pd.read_csv("data/urldata.csv")
df = df[["url", "label"]].dropna().copy()

label_map = {"good": 1, "bad": 0}
df["y"] = df["label"].str.lower().map(label_map)

if df["y"].isna().any():
    bad_values = df.loc[df["y"].isna(), "label"].unique()
    raise ValueError(f"Unexpected label values found: {bad_values}")

df.to_csv("data/labeled_url.csv",index=False)

print(df.head())
print(df["label"].value_counts())

                      url label  y
0  diaryofagameaddict.com   bad  0
1        espdesign.com.au   bad  0
2      iamagameaddict.com   bad  0
3           kalantzis.net   bad  0
4   slightlyoffcenter.net   bad  0
label
good    344821
bad      75643
Name: count, dtype: int64

In [136]:
df_good = df[df["y"] == 1].copy()
df_bad = df[df["y"] == 0].copy()

bad_train, bad_test = train_test_split(
    df_bad,
    test_size=0.2,
    random_state=42
)

train_df = pd.concat([df_good, bad_train]).sample(frac=1, random_state=42).reset_index(drop=True)

test_df = pd.concat([df_good, bad_test]).sample(frac=1, random_state=42).reset_index(drop=True)

X_train = train_df["url"].astype(str).str.strip().values
y_train = train_df["y"].values

X_test = test_df["url"].astype(str).str.strip().values
y_test = test_df["y"].values

In [137]:
def fast_sparse_vectorizer(X, num_bins=16384):
    strings = X.tolist() if isinstance(X, (pd.Series, np.ndarray)) else list(X)
    
    # Extract the raw C++ memory vectors
    data, indices, indptr = bloom.extract_sparse_ngrams(strings, num_bins)
    
    # Instantly construct the sparse matrix without Python loop overhead
    sparse_matrix = sp.csr_matrix((data, indices, indptr), shape=(len(strings), num_bins))
    
    return sparse_matrix

pipeline_vectorizer = FunctionTransformer(
    fast_sparse_vectorizer, 
    kw_args={"num_bins": N_FEATURES}
)

model = Pipeline(steps=[
    ("hash", pipeline_vectorizer),
    ("clf", SGDClassifier(
        loss="log_loss",
        alpha=1e-6,
        max_iter=100,
        tol=1e-3,
        class_weight="balanced",
        random_state=42
    ))
])

In [138]:
model.fit(X_train,y_train)

Pipeline(steps=[('hash',
                 FunctionTransformer(func=<function fast_sparse_vectorizer at 0x0000024D5AA26660>,
                                     kw_args={'num_bins': 16384})),
                ('clf',
                 SGDClassifier(alpha=1e-06, class_weight='balanced',
                               loss='log_loss', max_iter=100,
                               random_state=42))])

In [139]:
urls = X_test

start = time.perf_counter_ns()
X_features = model.named_steps["hash"].transform(urls)
end = time.perf_counter_ns()

feature_time = end - start

start = time.perf_counter_ns()
probs = model.named_steps["clf"].predict_proba(X_features)
end = time.perf_counter_ns()

clf_time = end - start

print(f"Feature extraction: {feature_time/1e6:.3f} ms")
print(f"Classifier:         {clf_time/1e6:.3f} ms")
print(f"Total:              {(feature_time+clf_time)/1e6:.3f} ms")

Feature extraction: 340.002 ms
Classifier:         73.939 ms
Total:              413.941 ms

In [140]:
y_pred = model.predict(X_test)
y_score = model.predict_proba(X_test)[:, 1]

print("AUC:", roc_auc_score(y_test, y_score))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

AUC: 0.9888235220735905
Confusion matrix:
 [[ 14038   1091]
 [  7210 337611]]
              precision    recall  f1-score   support

           0     0.6607    0.9279    0.7718     15129
           1     0.9968    0.9791    0.9879    344821

    accuracy                         0.9769    359950
   macro avg     0.8287    0.9535    0.8798    359950
weighted avg     0.9827    0.9769    0.9788    359950

In [141]:
def model_size_mb(trained_model) -> float:
    with tempfile.NamedTemporaryFile(suffix=".joblib", delete=False) as f:
        tmp = Path(f.name)
    joblib.dump(trained_model, tmp)
    size_mb = tmp.stat().st_size / (1024 * 1024)
    tmp.unlink(missing_ok=True)
    return size_mb

def run_ml_metrics_once(trained_model, X_eval, y_eval, threshold=0.5):
    t0 = time.perf_counter()
    scores = trained_model.predict_proba(X_eval)[:, 1]
    preds = (scores >= threshold).astype(int)
    t1 = time.perf_counter()

    tn, fp, fn, tp = confusion_matrix(y_eval, preds, labels=[0, 1]).ravel()

    negative_queries = int((y_eval == 0).sum())
    observed_fpr = fp / max(1, negative_queries)

    result = {
        "time_taken_ms": (t1 - t0) * 1000.0,
        "fp_count": int(fp),
        "negative_queries": int(negative_queries),
        "observed_fpr": float(observed_fpr),
        "true_positive": int(tp),
        "true_negative": int(tn),
        "false_negative": int(fn),
        "insert_count_analog": int((y_eval == 1).sum()),  
        "memory_needed_mb": model_size_mb(trained_model),
    }
    return result

ml_res = run_ml_metrics_once(model, X_test, y_test, threshold=0.5)
print(ml_res)

{'time_taken_ms': 379.826900025364, 'fp_count': 1091, 'negative_queries': 15129, 'observed_fpr': 0.0721131601559918, 'true_positive': 337611, 'true_negative': 14038, 'false_negative': 7210, 'insert_count_analog': 344821, 'memory_needed_mb': 0.06392765045166016}

In [142]:
print(f"Time taken: {ml_res['time_taken_ms']:.2f}ms")
print(f"FP: {ml_res['fp_count']}")
print(f"Total inserts: {ml_res['insert_count_analog']}")
print(f"Negative Queries: {ml_res['negative_queries']}")
print(f"Memory needed: {ml_res['memory_needed_mb']:.6f} MB")
print(f"Observed FP rate: {ml_res['observed_fpr']:.6f}")

Time taken: 379.83ms
FP: 1091
Total inserts: 344821
Negative Queries: 15129
Memory needed: 0.063928 MB
Observed FP rate: 0.072113

In [143]:
def evaluate_learned_bloom_with_backup(model, df, bloom_module=bloom, threshold_grid=None, target_fpr=0.01, output_csv="lbf_threshold_metrics.csv"):
    if threshold_grid is None:
        threshold_grid = np.linspace(0.05, 0.95, 37)

    positive_urls = df.loc[df["y"] == 1, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)
    negative_urls = df.loc[df["y"] == 0, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)

    pos_urls_arr = positive_urls.values
    neg_urls_arr = negative_urls.values

    num_pos = len(pos_urls_arr)
    num_neg = len(neg_urls_arr)

    vec_start_time = time.perf_counter()
    pos_scores = model.predict_proba(positive_urls)[:, 1]
    neg_scores = model.predict_proba(negative_urls)[:, 1]
    vec_end_time = time.perf_counter()

    vec_time = vec_end_time - vec_start_time
    print(vec_time)

    base_model_mb = model_size_mb(model)

    candidates = []

    for t in threshold_grid:
        start = time.perf_counter()
        
        pos_pred_model = pos_scores >= t
        neg_pred_model = neg_scores >= t

        model_fp_rate = float(neg_pred_model.mean())

        if model_fp_rate >= target_fpr:
            backup_fpr_target = 1e-9
        else:
            backup_fpr_target = (target_fpr - model_fp_rate) / max(1e-12, (1.0 - model_fp_rate))
            backup_fpr_target = min(max(backup_fpr_target, 1e-9), 0.99)

        rejected_pos_mask = ~pos_pred_model
        backup_keys = pos_urls_arr[rejected_pos_mask].tolist()

        backup_bf = bloom_module.BloomFilter(max(1, len(backup_keys)), backup_fpr_target)

        for key in backup_keys:
            backup_bf.add(key)

        fn = 0

        rejected_neg_urls = neg_urls_arr[~neg_pred_model].tolist()

        model_fp_count = int(neg_pred_model.sum())
        backup_fp_count = sum(backup_bf.contains(url) for url in rejected_neg_urls)

        fp = model_fp_count + backup_fp_count

        end = time.perf_counter()

        observed_fpr = fp / max(1, num_neg)

        backup_memory_mb = backup_bf.memory_cost() / (1024 * 1024)
        total_mb = base_model_mb + backup_memory_mb

        total_time = (end - start + vec_time) * 1000.0

        candidates.append({
            "threshold": float(t),
            "model_fp_rate": model_fp_rate,
            "backup_target_fpr": backup_fpr_target,
            "time_taken_ms": total_time,
            "time_per_query_ns": (total_time * 1000000) / (num_pos+num_neg), 
            "throughput_s": int(((num_pos + num_neg) * 1000) / max(total_time, 1e-6)),
            "insert_count": num_pos,
            "negative_queries": num_neg,
            "false_negative": fn,
            "false_positive": fp,
            "observed_fpr": observed_fpr,
            "model_memory_mb": base_model_mb,
            "backup_memory_mb": backup_memory_mb,
            "total_memory_mb": total_mb,
            "backup_key_count": len(backup_keys),
        })

    result_df = pd.DataFrame(candidates)

    result_df.to_csv(output_csv, index=False)
    print(f"Successfully evaluated {len(threshold_grid)} thresholds. Results saved to '{output_csv}'.")

    best_df = result_df.sort_values(
        by=["false_negative", "observed_fpr", "total_memory_mb", "time_taken_ms"]
    ).reset_index(drop=True)

    best = best_df.iloc[0].to_dict()
    return best, result_df

In [144]:
best_lbf, result_df = evaluate_learned_bloom_with_backup(
    model=model,
    df=df,
    target_fpr=TARGET_FPR,
    output_csv=f"results/result_{TARGET_FPR}_{N_FEATURES}.csv"
)

0.4607749999850057
Successfully evaluated 37 thresholds. Results saved to 'results/result_0.05_16384.csv'.

In [145]:
result_df

,threshold,model_fp_rate,backup_target_fpr,time_taken_ms,time_per_query_ns,throughput_s,insert_count,negative_queries,false_negative,false_positive,observed_fpr,model_memory_mb,backup_memory_mb,total_memory_mb,backup_key_count
0,0.050,0.095985,1.000000e-09,489.1959,1189.539888,840661,344800,66448,0,6378,0.095985,0.063928,0.012115,0.076043,2356
1,0.075,0.081387,1.000000e-09,481.3853,1170.547455,854301,344800,66448,0,5409,0.081402,0.063928,0.013931,0.077859,2709
2,0.100,0.071259,1.000000e-09,481.1224,1169.908182,854767,344800,66448,0,4735,0.071259,0.063928,0.015419,0.079347,2998
3,0.125,0.063493,1.000000e-09,481.8556,1171.691048,853467,344800,66448,0,4219,0.063493,0.063928,0.016937,0.080865,3294
4,0.150,0.056510,1.000000e-09,479.2477,1165.349619,858111,344800,66448,0,3755,0.056510,0.063928,0.018295,0.082223,3557
5,0.175,0.051213,1.000000e-09,478.2383,1162.895139,859922,344800,66448,0,3403,0.051213,0.063928,0.019699,0.083627,3830
6,0.200,0.046623,3.542226e-03,479.5528,1166.091507,857565,344800,66448,0,3310,0.049813,0.063928,0.005714,0.069642,4079
7,0.225,0.042650,7.677555e-03,481.2156,1170.134809,854602,344800,66448,0,3314,0.049874,0.063928,0.005249,0.069177,4341
8,0.250,0.039791,1.063256e-02,483.3582,1175.344804,850814,344800,66448,0,3316,0.049904,0.063928,0.005165,0.069093,4581
9,0.275,0.036811,1.369332e-02,480.6853,1168.845320,855545,344800,66448,0,3315,0.049889,0.063928,0.005142,0.069070,4826
10,0.300,0.034448,1.610686e-02,481.7516,1171.438159,853651,344800,66448,0,3351,0.050430,0.063928,0.005188,0.069116,5061
11,0.325,0.032762,1.782141e-02,480.8579,1169.265018,855238,344800,66448,0,3314,0.049874,0.063928,0.005325,0.069253,5325
12,0.350,0.030896,1.971271e-02,481.4929,1170.809098,854110,344800,66448,0,3268,0.049181,0.063928,0.005432,0.069360,5568
13,0.375,0.029136,2.149058e-02,482.4770,1173.202058,852368,344800,66448,0,3318,0.049934,0.063928,0.005554,0.069482,5826
14,0.400,0.027631,2.300501e-02,481.2543,1170.228913,854533,344800,66448,0,3329,0.050099,0.063928,0.005692,0.069619,6080
15,0.425,0.026472,2.416794e-02,483.5390,1175.784442,850496,344800,66448,0,3293,0.049558,0.063928,0.005867,0.069795,6344
16,0.450,0.025479,2.516254e-02,481.0366,1169.699549,854920,344800,66448,0,3315,0.049889,0.063928,0.006050,0.069978,6619
17,0.475,0.024380,2.626026e-02,483.9377,1176.753929,849795,344800,66448,0,3304,0.049723,0.063928,0.006226,0.070153,6893
18,0.500,0.023417,2.722061e-02,481.1487,1169.972134,854721,344800,66448,0,3331,0.050129,0.063928,0.006454,0.070382,7210
19,0.525,0.022393,2.823892e-02,481.4532,1170.712563,854180,344800,66448,0,3287,0.049467,0.063928,0.006653,0.070580,7511
20,0.550,0.021536,2.909085e-02,482.5101,1173.282545,852309,344800,66448,0,3297,0.049618,0.063928,0.006844,0.070771,7789
21,0.575,0.020663,2.995620e-02,482.6772,1173.688869,852014,344800,66448,0,3478,0.052342,0.063928,0.007080,0.071008,8126
22,0.600,0.020001,3.061165e-02,483.4529,1175.575079,850647,344800,66448,0,3245,0.048835,0.063928,0.007362,0.071290,8510
23,0.625,0.019293,3.131081e-02,483.5576,1175.829670,850463,344800,66448,0,3333,0.050160,0.063928,0.007622,0.071549,8860
24,0.650,0.018646,3.194958e-02,483.1381,1174.809604,851201,344800,66448,0,3334,0.050175,0.063928,0.007912,0.071839,9258
25,0.675,0.017909,3.267645e-02,482.5932,1173.484613,852162,344800,66448,0,3284,0.049422,0.063928,0.008209,0.072137,9671
26,0.700,0.017412,3.316537e-02,483.9324,1176.741042,849804,344800,66448,0,3286,0.049452,0.063928,0.008560,0.072488,10126
27,0.725,0.016870,3.369816e-02,485.5952,1180.784344,846894,344800,66448,0,3280,0.049362,0.063928,0.008919,0.072846,10600
28,0.750,0.016253,3.430425e-02,484.0353,1176.991256,849623,344800,66448,0,3394,0.051078,0.063928,0.009293,0.073220,11105
29,0.775,0.015727,3.482103e-02,485.7251,1181.100212,846668,344800,66448,0,3290,0.049512,0.063928,0.009705,0.073632,11648
30,0.800,0.015230,3.530778e-02,489.5922,1190.503540,839980,344800,66448,0,3316,0.049904,0.063928,0.010223,0.074151,12321
31,0.825,0.014628,3.589712e-02,484.1218,1177.201591,849472,344800,66448,0,3391,0.051032,0.063928,0.010803,0.074731,13082
32,0.850,0.013996,3.651516e-02,484.9028,1179.100689,848103,344800,66448,0,3357,0.050521,0.063928,0.011429,0.075356,13909
33,0.875,0.013289,3.720583e-02,485.3876,1180.279539,847256,344800,66448,0,3306,0.049753,0.063928,0.012154,0.076081,14881
34,0.900,0.012672,3.780752e-02,487.6873,1185.871542,843261,344800,66448,0,3343,0.050310,0.063928,0.013084,0.077012,16095
35,0.925,0.012009,3.845240e-02,488.8240,1188.635568,841300,344800,66448,0,3307,0.049768,0.063928,0.014305,0.078233,17686
36,0.950,0.011212,3.922804e-02,485.6114,1180.823736,846866,344800,66448,0,3160,0.047556,0.063928,0.015930,0.079858,19819

In [146]:
best_lbf

{'threshold': 0.95,
 'model_fp_rate': 0.01121177462075608,
 'backup_target_fpr': 0.039228041337534054,
 'time_taken_ms': 485.61139998491853,
 'time_per_query_ns': 1180.8237364921374,
 'throughput_s': 846866.0,
 'insert_count': 344800.0,
 'negative_queries': 66448.0,
 'false_negative': 0.0,
 'false_positive': 3160.0,
 'observed_fpr': 0.04755598362629424,
 'model_memory_mb': 0.06392765045166016,
 'backup_memory_mb': 0.01593017578125,
 'total_memory_mb': 0.07985782623291016,
 'backup_key_count': 19819.0}