In [17]:
import re
import json
import math
import time
import tempfile
import subprocess
from pathlib import Path

import os
os.add_dll_directory("C:/msys64/ucrt64/bin")
import cppbloom as bloom

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.sparse as sp

from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.base import BaseEstimator, TransformerMixin
from scipy.sparse import csr_matrix
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, precision_recall_curve, classification_report, confusion_matrix
import joblib

In [18]:
PROJECT_DIR = Path(".")
DATA_PATH = PROJECT_DIR / "data" / "urldata.csv"

TARGET_FPR = 0.05
N_REPEATS = 8
RANDOM_STATE = 42

In [19]:
def run_baseline_once() -> dict:
    eval = bloom.Evaluator()
    res = eval.run_single_experiment(400000,TARGET_FPR,"data/real.txt","data/fake.txt")

    result = {}

    result["time_ms"] = res.timeTakenInNs / 1000000.0
    result["fp_count"] = res.falsePositive
    result["insert_count"] = res.insertCount
    result["negative_queries"] = res.negativeQueryCount
    result["memory_mb"] = res.memoryNeeded / (1024*1024)
    result["time_per_query_ns"] = res.timeTakenInNs / (res.negativeQueryCount+res.insertCount)
    result["throughtput_s"] = (res.insertCount+res.negativeQueryCount) / (res.timeTakenInNs / 1000000000)

    result["observed_fpr"] = result["fp_count"] / max(1, result["negative_queries"])
    return result

In [20]:
baseline_rows = []
for i in range(N_REPEATS):
    row = run_baseline_once()
    row["trial"] = i + 1
    baseline_rows.append(row)

baseline_df = pd.DataFrame(baseline_rows)

summary = baseline_df.agg({
    "time_ms": ["mean", "std"],
    "throughtput_s" : ["mean", "std"],
    "memory_mb": ["mean", "std"],
    "time_per_query_ns": ["mean", "std"],
    "observed_fpr": ["mean", "std"],
    "fp_count": ["mean", "std"],
    "insert_count": ["mean", "std"],
    "negative_queries": ["mean", "std"],
})
display(baseline_df)
display(summary)

,time_ms,fp_count,insert_count,negative_queries,memory_mb,time_per_query_ns,throughtput_s,observed_fpr,trial
0,53.7936,2560,344928,75536,0.297325,127.938658,7.816246e+06,0.033891,1
1,60.6743,2560,344928,75536,0.297325,144.303198,6.929853e+06,0.033891,2
2,50.5890,2560,344928,75536,0.297325,120.317078,8.311372e+06,0.033891,3
3,49.8821,2560,344928,75536,0.297325,118.635840,8.429156e+06,0.033891,4
4,50.7710,2560,344928,75536,0.297325,120.749933,8.281578e+06,0.033891,5
5,51.1076,2560,344928,75536,0.297325,121.550478,8.227035e+06,0.033891,6
6,50.2242,2560,344928,75536,0.297325,119.449465,8.371741e+06,0.033891,7
7,49.2811,2560,344928,75536,0.297325,117.206467,8.531952e+06,0.033891,8

,time_ms,throughtput_s,memory_mb,time_per_query_ns,observed_fpr,fp_count,insert_count,negative_queries
mean,52.040363,8.112367e+06,0.297325,123.768890,0.033891,2560.0,344928.0,75536.0
std,3.737390,5.225067e+05,0.000000,8.888727,0.000000,0.0,0.0,0.0

In [21]:
df = pd.read_csv("data/urldata.csv")
df = df[["url", "label"]].dropna().copy()

label_map = {"good": 1, "bad": 0}
df["y"] = df["label"].str.lower().map(label_map)

if df["y"].isna().any():
    bad_values = df.loc[df["y"].isna(), "label"].unique()
    raise ValueError(f"Unexpected label values found: {bad_values}")

df.to_csv("data/labeled_url.csv",index=False)

print(df.head())
print(df["label"].value_counts())

                      url label  y
0  diaryofagameaddict.com   bad  0
1        espdesign.com.au   bad  0
2      iamagameaddict.com   bad  0
3           kalantzis.net   bad  0
4   slightlyoffcenter.net   bad  0
label
good    344821
bad      75643
Name: count, dtype: int64

In [22]:
df_good = df[df["y"] == 1].copy()
df_bad = df[df["y"] == 0].copy()

bad_train, bad_test = train_test_split(
    df_bad,
    test_size=0.2,
    random_state=42
)

train_df = pd.concat([df_good, bad_train]).sample(frac=1, random_state=42).reset_index(drop=True)

test_df = pd.concat([df_good, bad_test]).sample(frac=1, random_state=42).reset_index(drop=True)

X_train = train_df["url"].astype(str).str.strip().values
y_train = train_df["y"].values

X_test = test_df["url"].astype(str).str.strip().values
y_test = test_df["y"].values

In [23]:
def fast_sparse_vectorizer(X, num_bins=16384): # We now have enough bins to stop collisions
    strings = X.tolist() if isinstance(X, (pd.Series, np.ndarray)) else list(X)
    
    # Extract the raw C++ memory vectors
    data, indices, indptr = bloom.extract_sparse_ngrams_cpp(strings, num_bins)
    
    # Instantly construct the sparse matrix without Python loop overhead
    sparse_matrix = sp.csr_matrix((data, indices, indptr), shape=(len(strings), num_bins))
    
    return sparse_matrix

pipeline_vectorizer = FunctionTransformer(
    fast_sparse_vectorizer, 
    kw_args={"num_bins": 16384}
)

model = Pipeline(steps=[
    ("hash", pipeline_vectorizer),
    ("clf", SGDClassifier(
        loss="log_loss",
        alpha=1e-6,
        max_iter=40,
        tol=1e-3,
        class_weight="balanced",
        random_state=42
    ))
])

In [24]:
model.fit(X_train,y_train)

c:\Users\hemti\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_stochastic_gradient.py:726: ConvergenceWarning: Maximum number of iteration reached before convergence. Consider increasing max_iter to improve the fit.
  warnings.warn(

Pipeline(steps=[('hash',
                 FunctionTransformer(func=<function fast_sparse_vectorizer at 0x0000026ED2637CE0>,
                                     kw_args={'num_bins': 16384})),
                ('clf',
                 SGDClassifier(alpha=1e-06, class_weight='balanced',
                               loss='log_loss', max_iter=40,
                               random_state=42))])

In [25]:
urls = X_test

start = time.perf_counter_ns()
X_features = model.named_steps["hash"].transform(urls)
end = time.perf_counter_ns()

feature_time = end - start

start = time.perf_counter_ns()
probs = model.named_steps["clf"].predict_proba(X_features)
end = time.perf_counter_ns()

clf_time = end - start

print(f"Feature extraction: {feature_time/1e6:.3f} ms")
print(f"Classifier:         {clf_time/1e6:.3f} ms")
print(f"Total:              {(feature_time+clf_time)/1e6:.3f} ms")

Feature extraction: 380.102 ms
Classifier:         68.903 ms
Total:              449.005 ms

In [26]:
y_pred = model.predict(X_test)
y_score = model.predict_proba(X_test)[:, 1]

print("AUC:", roc_auc_score(y_test, y_score))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

AUC: 0.988178894046343
Confusion matrix:
 [[ 14075   1054]
 [  9393 335428]]
              precision    recall  f1-score   support

           0     0.5998    0.9303    0.7293     15129
           1     0.9969    0.9728    0.9847    344821

    accuracy                         0.9710    359950
   macro avg     0.7983    0.9515    0.8570    359950
weighted avg     0.9802    0.9710    0.9739    359950

In [27]:
def model_size_mb(trained_model) -> float:
    with tempfile.NamedTemporaryFile(suffix=".joblib", delete=False) as f:
        tmp = Path(f.name)
    joblib.dump(trained_model, tmp)
    size_mb = tmp.stat().st_size / (1024 * 1024)
    tmp.unlink(missing_ok=True)
    return size_mb

def run_ml_metrics_once(trained_model, X_eval, y_eval, threshold=0.5):
    t0 = time.perf_counter()
    scores = trained_model.predict_proba(X_eval)[:, 1]
    preds = (scores >= threshold).astype(int)
    t1 = time.perf_counter()

    tn, fp, fn, tp = confusion_matrix(y_eval, preds, labels=[0, 1]).ravel()

    negative_queries = int((y_eval == 0).sum())
    observed_fpr = fp / max(1, negative_queries)

    result = {
        "time_taken_ms": (t1 - t0) * 1000.0,
        "fp_count": int(fp),
        "negative_queries": int(negative_queries),
        "observed_fpr": float(observed_fpr),
        "true_positive": int(tp),
        "true_negative": int(tn),
        "false_negative": int(fn),
        "insert_count_analog": int((y_eval == 1).sum()),  
        "memory_needed_mb": model_size_mb(trained_model),
    }
    return result

ml_res = run_ml_metrics_once(model, X_test, y_test, threshold=0.5)
print(ml_res)

{'time_taken_ms': 522.2565000003669, 'fp_count': 1054, 'negative_queries': 15129, 'observed_fpr': 0.06966752594355212, 'true_positive': 335428, 'true_negative': 14075, 'false_negative': 9393, 'insert_count_analog': 344821, 'memory_needed_mb': 0.06392765045166016}

In [28]:
print(f"Time taken: {ml_res['time_taken_ms']:.2f}ms")
print(f"FP: {ml_res['fp_count']}")
print(f"Total inserts: {ml_res['insert_count_analog']}")
print(f"Negative Queries: {ml_res['negative_queries']}")
print(f"Memory needed: {ml_res['memory_needed_mb']:.6f} MB")
print(f"Observed FP rate: {ml_res['observed_fpr']:.6f}")

Time taken: 522.26ms
FP: 1054
Total inserts: 344821
Negative Queries: 15129
Memory needed: 0.063928 MB
Observed FP rate: 0.069668

In [29]:
def evaluate_learned_bloom_with_backup(model, df, bloom_module=bloom, threshold_grid=None, target_fpr=0.01, output_csv="lbf_threshold_metrics.csv"):
    if threshold_grid is None:
        threshold_grid = np.linspace(0.05, 0.95, 37)

    positive_urls = df.loc[df["y"] == 1, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)
    negative_urls = df.loc[df["y"] == 0, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)

    pos_urls_arr = positive_urls.values
    neg_urls_arr = negative_urls.values

    num_pos = len(pos_urls_arr)
    num_neg = len(neg_urls_arr)

    vec_start_time = time.perf_counter()
    pos_scores = model.predict_proba(positive_urls)[:, 1]
    neg_scores = model.predict_proba(negative_urls)[:, 1]
    vec_end_time = time.perf_counter()

    vec_time = vec_end_time - vec_start_time
    print(vec_time)

    base_model_mb = model_size_mb(model)

    candidates = []

    for t in threshold_grid:
        pos_pred_model = pos_scores >= t
        neg_pred_model = neg_scores >= t

        model_fp_rate = float(neg_pred_model.mean())

        if model_fp_rate >= target_fpr:
            backup_fpr_target = 1e-9
        else:
            backup_fpr_target = (target_fpr - model_fp_rate) / max(1e-12, (1.0 - model_fp_rate))
            backup_fpr_target = min(max(backup_fpr_target, 1e-9), 0.99)

        rejected_pos_mask = ~pos_pred_model
        backup_keys = pos_urls_arr[rejected_pos_mask].tolist()

        backup_bf = bloom_module.BloomFilter(max(1, len(backup_keys)), backup_fpr_target)

        for key in backup_keys:
            backup_bf.add(key)

        start = time.perf_counter()

        fn = 0

        rejected_neg_urls = neg_urls_arr[~neg_pred_model].tolist()

        model_fp_count = int(neg_pred_model.sum())
        backup_fp_count = sum(backup_bf.contains(url) for url in rejected_neg_urls)

        fp = model_fp_count + backup_fp_count

        end = time.perf_counter()

        observed_fpr = fp / max(1, num_neg)

        backup_memory_mb = backup_bf.memory_cost() / (1024 * 1024)
        total_mb = base_model_mb + backup_memory_mb

        total_time = (end - start + vec_time) * 1000.0

        candidates.append({
            "threshold": float(t),
            "model_fp_rate": model_fp_rate,
            "backup_target_fpr": backup_fpr_target,
            "time_taken_ms": total_time,
            "throughput_s": (num_pos + num_neg) * 1000 / max(total_time, 1e-6),
            "insert_count": num_pos,
            "negative_queries": num_neg,
            "false_negative": fn,
            "false_positive": fp,
            "observed_fpr": observed_fpr,
            "model_memory_mb": base_model_mb,
            "backup_memory_mb": backup_memory_mb,
            "total_memory_mb": total_mb,
            "backup_key_count": len(backup_keys),
        })

    result_df = pd.DataFrame(candidates)

    result_df.to_csv(output_csv, index=False)
    print(f"Successfully evaluated {len(threshold_grid)} thresholds. Results saved to '{output_csv}'.")

    best_df = result_df.sort_values(
        by=["false_negative", "observed_fpr", "total_memory_mb", "time_taken_ms"]
    ).reset_index(drop=True)

    best = best_df.iloc[0].to_dict()
    return best, result_df

In [30]:
best_lbf, result_df = evaluate_learned_bloom_with_backup(
    model=model,
    df=df,
    target_fpr=TARGET_FPR,
    output_csv=f"results/result_{TARGET_FPR}.csv"
)

0.4966402999998536
Successfully evaluated 37 thresholds. Results saved to 'results/result_0.05.csv'.

In [31]:
result_df

,threshold,model_fp_rate,backup_target_fpr,time_taken_ms,throughput_s,insert_count,negative_queries,false_negative,false_positive,observed_fpr,model_memory_mb,backup_memory_mb,total_memory_mb,backup_key_count
0,0.050,0.056751,1.000000e-09,520.5525,790022.139929,344800,66448,0,3771,0.056751,0.063928,0.026421,0.090348,5138
1,0.075,0.051183,1.000000e-09,522.1336,787629.832677,344800,66448,0,3401,0.051183,0.063928,0.028923,0.092851,5624
2,0.100,0.047827,2.282282e-03,520.5765,789985.717758,344800,66448,0,3340,0.050265,0.063928,0.009033,0.072961,5983
3,0.125,0.044787,5.457525e-03,520.3893,790269.899862,344800,66448,0,3308,0.049783,0.063928,0.008141,0.072068,6296
4,0.150,0.042153,8.192059e-03,517.6332,794477.633973,344800,66448,0,3319,0.049949,0.063928,0.007820,0.071748,6556
5,0.175,0.040182,1.022923e-02,520.9580,789407.207478,344800,66448,0,3318,0.049934,0.063928,0.007751,0.071679,6814
6,0.200,0.038481,1.197978e-02,522.6635,786831.297766,344800,66448,0,3336,0.050205,0.063928,0.007729,0.071656,7037
7,0.225,0.037006,1.349294e-02,519.2894,791943.760059,344800,66448,0,3386,0.050957,0.063928,0.007774,0.071702,7274
8,0.250,0.035652,1.487851e-02,520.6805,789827.927099,344800,66448,0,3296,0.049603,0.063928,0.007812,0.071740,7481
9,0.275,0.034553,1.599950e-02,518.7950,792698.464695,344800,66448,0,3326,0.050054,0.063928,0.007881,0.071809,7681
10,0.300,0.033455,1.711794e-02,520.8132,789626.683814,344800,66448,0,3296,0.049603,0.063928,0.007942,0.071870,7866
11,0.325,0.032552,1.803531e-02,521.8113,788116.317142,344800,66448,0,3314,0.049874,0.063928,0.008018,0.071946,8043
12,0.350,0.031784,1.881373e-02,520.3374,790348.723736,344800,66448,0,3382,0.050897,0.063928,0.008102,0.072030,8218
13,0.375,0.031002,1.960614e-02,518.5634,793052.498486,344800,66448,0,3380,0.050867,0.063928,0.008240,0.072167,8441
14,0.400,0.030294,2.032125e-02,518.3940,793311.650985,344800,66448,0,3364,0.050626,0.063928,0.008331,0.072259,8613
15,0.425,0.029286,2.133887e-02,519.5262,791582.792159,344800,66448,0,3290,0.049512,0.063928,0.008385,0.072312,8779
16,0.450,0.028594,2.203631e-02,520.2578,790469.647928,344800,66448,0,3254,0.048971,0.063928,0.008484,0.072412,8957
17,0.475,0.027856,2.277815e-02,519.7732,791206.626283,344800,66448,0,3321,0.049979,0.063928,0.008614,0.072541,9176
18,0.500,0.026999,2.363968e-02,518.1318,793713.105414,344800,66448,0,3264,0.049121,0.063928,0.008728,0.072656,9393
19,0.525,0.026487,2.415286e-02,518.9315,792489.952909,344800,66448,0,3288,0.049482,0.063928,0.008842,0.072770,9568
20,0.550,0.025599,2.504209e-02,520.1764,790593.344860,344800,66448,0,3319,0.049949,0.063928,0.008919,0.072846,9745
21,0.575,0.024982,2.565907e-02,518.6415,792933.076136,344800,66448,0,3377,0.050822,0.063928,0.009026,0.072953,9930
22,0.600,0.024395,2.624524e-02,519.6099,791455.282123,344800,66448,0,3325,0.050039,0.063928,0.009155,0.073083,10132
23,0.625,0.023838,2.680069e-02,521.7529,788204.531291,344800,66448,0,3311,0.049828,0.063928,0.009285,0.073213,10338
24,0.650,0.023251,2.738548e-02,520.0527,790781.395812,344800,66448,0,3324,0.050024,0.063928,0.009438,0.073365,10572
25,0.675,0.022589,2.804441e-02,522.2313,787482.481425,344800,66448,0,3328,0.050084,0.063928,0.009575,0.073503,10795
26,0.700,0.021927,2.870244e-02,520.1085,790696.556583,344800,66448,0,3330,0.050114,0.063928,0.009735,0.073663,11043
27,0.725,0.021280,2.934465e-02,520.1018,790706.742421,344800,66448,0,3381,0.050882,0.063928,0.009926,0.073853,11330
28,0.750,0.020738,2.988167e-02,519.3823,791802.108003,344800,66448,0,3222,0.048489,0.063928,0.010117,0.074044,11609
29,0.775,0.020106,3.050743e-02,519.7076,791306.496185,344800,66448,0,3343,0.050310,0.063928,0.010315,0.074243,11910
30,0.800,0.019459,3.114726e-02,518.2145,793586.439592,344800,66448,0,3386,0.050957,0.063928,0.010536,0.074464,12237
31,0.825,0.018691,3.190504e-02,519.9498,790937.894389,344800,66448,0,3333,0.050160,0.063928,0.010788,0.074716,12616
32,0.850,0.018074,3.251337e-02,520.7928,789657.614311,344800,66448,0,3409,0.051303,0.063928,0.011070,0.074998,13020
33,0.875,0.017548,3.303208e-02,520.2721,790447.921393,344800,66448,0,3343,0.050310,0.063928,0.011444,0.075372,13516
34,0.900,0.016750,3.381648e-02,519.3174,791901.060890,344800,66448,0,3266,0.049151,0.063928,0.011902,0.075830,14157
35,0.925,0.015712,3.483579e-02,518.6854,792865.964601,344800,66448,0,3270,0.049211,0.063928,0.012497,0.076425,14995
36,0.950,0.014778,3.574985e-02,520.4167,790228.292052,344800,66448,0,3363,0.050611,0.063928,0.013359,0.077287,16159

In [32]:
best_lbf

{'threshold': 0.75,
 'model_fp_rate': 0.020738020707921984,
 'backup_target_fpr': 0.02988166589826341,
 'time_taken_ms': 519.3823000008706,
 'throughput_s': 791802.1080027383,
 'insert_count': 344800.0,
 'negative_queries': 66448.0,
 'false_negative': 0.0,
 'false_positive': 3222.0,
 'observed_fpr': 0.04848904406453167,
 'model_memory_mb': 0.06392765045166016,
 'backup_memory_mb': 0.0101165771484375,
 'total_memory_mb': 0.07404422760009766,
 'backup_key_count': 11609.0}