In [39]:
import re
import json
import math
import time
import tempfile
import subprocess
from pathlib import Path

import os
os.add_dll_directory("C:/msys64/ucrt64/bin")
import cppbloom as bloom

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.pipeline import Pipeline, FeatureUnion
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.linear_model import SGDClassifier
from sklearn.base import BaseEstimator, TransformerMixin
from scipy.sparse import csr_matrix
from sklearn.preprocessing import FunctionTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, precision_recall_curve, classification_report, confusion_matrix
import joblib

In [40]:
PROJECT_DIR = Path(".")
DATA_PATH = PROJECT_DIR / "data" / "urldata.csv"

TARGET_FPR = 0.01
N_REPEATS = 8
RANDOM_STATE = 42

In [41]:
def run_baseline_once() -> dict:
    eval = bloom.Evaluator()
    res = eval.run_single_experiment(400000,TARGET_FPR,"data/real.txt","data/fake.txt")

    result = {}

    result["time_ms"] = res.timeTakenInNs / 1000000.0
    result["fp_count"] = res.falsePositive
    result["insert_count"] = res.insertCount
    result["negative_queries"] = res.negativeQueryCount
    result["memory_mb"] = res.memoryNeeded / (1024*1024)
    result["time_per_query_ns"] = res.timeTakenInNs / (res.negativeQueryCount+res.insertCount)
    result["throughtput_s"] = (res.insertCount+res.negativeQueryCount) / (res.timeTakenInNs / 1000000000)

    result["observed_fpr"] = result["fp_count"] / max(1, result["negative_queries"])
    return result

In [42]:
baseline_rows = []
for i in range(N_REPEATS):
    row = run_baseline_once()
    row["trial"] = i + 1
    baseline_rows.append(row)

baseline_df = pd.DataFrame(baseline_rows)

summary = baseline_df.agg({
    "time_ms": ["mean", "std"],
    "throughtput_s" : ["mean", "std"],
    "memory_mb": ["mean", "std"],
    "time_per_query_ns": ["mean", "std"],
    "observed_fpr": ["mean", "std"],
    "fp_count": ["mean", "std"],
    "insert_count": ["mean", "std"],
    "negative_queries": ["mean", "std"],
})
display(baseline_df)
display(summary)

,time_ms,fp_count,insert_count,negative_queries,memory_mb,time_per_query_ns,throughtput_s,observed_fpr,trial
0,53.8806,335,344928,75536,0.457054,128.145573,7.803625e+06,0.004435,1
1,81.3990,335,344928,75536,0.457054,193.593268,5.165469e+06,0.004435,2
2,63.8642,335,344928,75536,0.457054,151.889817,6.583720e+06,0.004435,3
3,87.9423,335,344928,75536,0.457054,209.155362,4.781135e+06,0.004435,4
4,73.7031,335,344928,75536,0.457054,175.289918,5.704835e+06,0.004435,5
5,74.0766,335,344928,75536,0.457054,176.178222,5.676070e+06,0.004435,6
6,77.3694,335,344928,75536,0.457054,184.009570,5.434500e+06,0.004435,7
7,80.8857,335,344928,75536,0.457054,192.372474,5.198249e+06,0.004435,8

,time_ms,throughtput_s,memory_mb,time_per_query_ns,observed_fpr,fp_count,insert_count,negative_queries
mean,74.140113,5.793450e+06,0.457054,176.329276,0.004435,335.0,344928.0,75536.0
std,10.792592,9.702144e+05,0.000000,25.668291,0.000000,0.0,0.0,0.0

In [43]:
df = pd.read_csv("data/urldata.csv")
df = df[["url", "label"]].dropna().copy()

label_map = {"good": 1, "bad": 0}
df["y"] = df["label"].str.lower().map(label_map)

if df["y"].isna().any():
    bad_values = df.loc[df["y"].isna(), "label"].unique()
    raise ValueError(f"Unexpected label values found: {bad_values}")

df.to_csv("data/labeled_url.csv",index=False)

print(df.head())
print(df["label"].value_counts())

                      url label  y
0  diaryofagameaddict.com   bad  0
1        espdesign.com.au   bad  0
2      iamagameaddict.com   bad  0
3           kalantzis.net   bad  0
4   slightlyoffcenter.net   bad  0
label
good    344821
bad      75643
Name: count, dtype: int64

In [44]:
X = df["url"].astype(str).str.strip()
y = df["y"].values

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print("Train shape:", X_train.shape, "Test shape:", X_test.shape)

Train shape: (294324,) Test shape: (126140,)

In [45]:
model = Pipeline(steps=[
    ("hash", HashingVectorizer(
        analyzer="char_wb",
        ngram_range=(3, 5),
        n_features=2**14,
        alternate_sign=False,
        lowercase=True
    )),
    ("clf", SGDClassifier(
        loss="log_loss",
        alpha=1e-6,
        max_iter=40,
        tol=1e-3,
        class_weight="balanced",
        random_state=42
    ))
])

In [46]:
model.fit(X_train,y_train)

Pipeline(steps=[('hash',
                 HashingVectorizer(alternate_sign=False, analyzer='char_wb',
                                   n_features=16384, ngram_range=(3, 5))),
                ('clf',
                 SGDClassifier(alpha=1e-06, class_weight='balanced',
                               loss='log_loss', max_iter=40,
                               random_state=42))])

In [47]:
y_pred = model.predict(X_test)
y_score = model.predict_proba(X_test)[:, 1]

print("AUC:", roc_auc_score(y_test, y_score))
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, digits=4))

AUC: 0.9928888268066134
Confusion matrix:
 [[ 21737    956]
 [  3292 100155]]
              precision    recall  f1-score   support

           0     0.8685    0.9579    0.9110     22693
           1     0.9905    0.9682    0.9792    103447

    accuracy                         0.9663    126140
   macro avg     0.9295    0.9630    0.9451    126140
weighted avg     0.9686    0.9663    0.9670    126140

In [48]:
def model_size_mb(trained_model) -> float:
    with tempfile.NamedTemporaryFile(suffix=".joblib", delete=False) as f:
        tmp = Path(f.name)
    joblib.dump(trained_model, tmp)
    size_mb = tmp.stat().st_size / (1024 * 1024)
    tmp.unlink(missing_ok=True)
    return size_mb

def run_ml_metrics_once(trained_model, X_eval, y_eval, threshold=0.5):
    t0 = time.perf_counter()
    scores = trained_model.predict_proba(X_eval)[:, 1]
    preds = (scores >= threshold).astype(int)
    t1 = time.perf_counter()

    tn, fp, fn, tp = confusion_matrix(y_eval, preds, labels=[0, 1]).ravel()

    negative_queries = int((y_eval == 0).sum())
    observed_fpr = fp / max(1, negative_queries)

    result = {
        "time_taken_ms": (t1 - t0) * 1000.0,
        "fp_count": int(fp),
        "negative_queries": int(negative_queries),
        "observed_fpr": float(observed_fpr),
        "true_positive": int(tp),
        "true_negative": int(tn),
        "false_negative": int(fn),
        "insert_count_analog": int((y_eval == 1).sum()),  
        "memory_needed_mb": model_size_mb(trained_model),
    }
    return result

ml_res = run_ml_metrics_once(model, X_test, y_test, threshold=0.5)
print(ml_res)

{'time_taken_ms': 7421.618099993793, 'fp_count': 956, 'negative_queries': 22693, 'observed_fpr': 0.04212752831269555, 'true_positive': 100155, 'true_negative': 21737, 'false_negative': 3292, 'insert_count_analog': 103447, 'memory_needed_mb': 0.12648868560791016}

In [49]:
print(f"Time taken: {ml_res['time_taken_ms']:.2f}ms")
print(f"FP: {ml_res['fp_count']}")
print(f"Total inserts: {ml_res['insert_count_analog']}")
print(f"Negative Queries: {ml_res['negative_queries']}")
print(f"Memory needed: {ml_res['memory_needed_mb']:.6f} MB")
print(f"Observed FP rate: {ml_res['observed_fpr']:.6f}")

Time taken: 7421.62ms
FP: 956
Total inserts: 103447
Negative Queries: 22693
Memory needed: 0.126489 MB
Observed FP rate: 0.042128

In [54]:
def evaluate_learned_bloom_with_backup(model, df, bloom_module = bloom, threshold_grid=None, target_fpr=0.01, output_csv="lbf_threshold_metrics.csv"):
    if threshold_grid is None:
        threshold_grid = np.linspace(0.05, 0.95, 37)

    positive_urls = df.loc[df["y"] == 1, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)
    negative_urls = df.loc[df["y"] == 0, "url"].dropna().astype(str).drop_duplicates().reset_index(drop=True)

    pos_scores = model.predict_proba(positive_urls)[:, 1]
    neg_scores = model.predict_proba(negative_urls)[:, 1]

    base_model_mb = model_size_mb(model)

    candidates = []

    for t in threshold_grid:
        model_fp_rate = float((neg_scores >= t).mean())
        
        if model_fp_rate >= target_fpr:
            backup_fpr_target = 1e-9 
        else:
            backup_fpr_target = (target_fpr - model_fp_rate) / max(1e-12, (1.0 - model_fp_rate))
            backup_fpr_target = min(max(backup_fpr_target, 1e-9), 0.99)

        backup_keys = positive_urls[pos_scores < t].tolist()
        backup_bf = bloom_module.BloomFilter(max(1, len(backup_keys)), backup_fpr_target)

        for key in backup_keys:
            backup_bf.add(key)

        start = time.perf_counter()
        
        pos_pred_model = pos_scores >= t
        neg_pred_model = neg_scores >= t

        pos_pred_system = pos_pred_model.copy()
        rejected_pos_idx = np.where(~pos_pred_model)[0]
        
        for idx in rejected_pos_idx:
            if backup_bf.contains(positive_urls.iloc[idx]):
                pos_pred_system[idx] = True

        neg_pred_system = neg_pred_model.copy()
        rejected_neg_idx = np.where(~neg_pred_model)[0]
        
        for idx in rejected_neg_idx:
            if backup_bf.contains(negative_urls.iloc[idx]):
                neg_pred_system[idx] = True
                
        end = time.perf_counter()

        fn = int((~pos_pred_system).sum())
        fp = int(neg_pred_system.sum())
        observed_fpr = fp / max(1, len(negative_urls))

        backup_memory_mb = (backup_bf.memory_cost() / (1024 * 1024))
        total_mb = base_model_mb + backup_memory_mb

        candidates.append({
            "threshold": float(t),
            "model_fp_rate": model_fp_rate,
            "backup_target_fpr": backup_fpr_target,
            "time_taken_ms": ((end - start) * 1000.0),
            "throughput_s" : (int(len(positive_urls))+int(len(negative_urls))) / (end - start), 
            "insert_count": int(len(positive_urls)),
            "negative_queries": int(len(negative_urls)),
            "false_negative": fn,
            "false_positive": fp,
            "observed_fpr": observed_fpr,
            "model_memory_mb": base_model_mb,
            "backup_memory_mb": backup_memory_mb,
            "total_memory_mb": total_mb,
            "backup_key_count": int(len(backup_keys)),
        })

    result_df = pd.DataFrame(candidates)
    
    result_df.to_csv(output_csv, index=False)
    print(f"Successfully evaluated {len(threshold_grid)} thresholds. Results saved to '{output_csv}'.")

    best_df = result_df.sort_values(
        by=["false_negative", "observed_fpr", "total_memory_mb", "time_taken_ms"]
    ).reset_index(drop=True)

    best = best_df.iloc[0].to_dict()
    return best, result_df

In [55]:
best_lbf, result_df = evaluate_learned_bloom_with_backup(
    model=model,
    df=df,
    target_fpr=TARGET_FPR,
    output_csv=f"results/result_{TARGET_FPR}.csv"
)

Successfully evaluated 37 thresholds. Results saved to 'results/result_0.01.csv'.

In [56]:
result_df

,threshold,model_fp_rate,backup_target_fpr,time_taken_ms,throughput_s,insert_count,negative_queries,false_negative,false_positive,observed_fpr,model_memory_mb,backup_memory_mb,total_memory_mb,backup_key_count
0,0.050,0.234770,1.000000e-09,539.8398,7.617964e+05,344800,66448,0,15600,0.234770,0.126489,0.003204,0.129693,623
1,0.075,0.188659,1.000000e-09,581.6218,7.070712e+05,344800,66448,0,12537,0.188674,0.126489,0.004593,0.131082,892
2,0.100,0.156814,1.000000e-09,581.5359,7.071756e+05,344800,66448,0,10420,0.156814,0.126489,0.006126,0.132615,1191
3,0.125,0.133382,1.000000e-09,536.7699,7.661532e+05,344800,66448,0,8863,0.133382,0.126489,0.007744,0.134233,1505
4,0.150,0.115880,1.000000e-09,657.5765,6.253995e+05,344800,66448,0,7700,0.115880,0.126489,0.009583,0.136071,1863
5,0.175,0.101990,1.000000e-09,587.0640,7.005165e+05,344800,66448,0,6777,0.101990,0.126489,0.011230,0.137719,2184
6,0.200,0.089694,1.000000e-09,683.1140,6.020196e+05,344800,66448,0,5960,0.089694,0.126489,0.013107,0.139596,2549
7,0.225,0.079822,1.000000e-09,656.3619,6.265568e+05,344800,66448,0,5304,0.079822,0.126489,0.015144,0.141633,2945
8,0.250,0.070898,1.000000e-09,606.7574,6.777799e+05,344800,66448,0,4711,0.070898,0.126489,0.017159,0.143647,3337
9,0.275,0.063538,1.000000e-09,631.9380,6.507727e+05,344800,66448,0,4222,0.063538,0.126489,0.019424,0.145913,3777
10,0.300,0.057775,1.000000e-09,760.7731,5.405659e+05,344800,66448,0,3839,0.057775,0.126489,0.021767,0.148255,4232
11,0.325,0.052432,1.000000e-09,429.9239,9.565600e+05,344800,66448,0,3484,0.052432,0.126489,0.024170,0.150659,4700
12,0.350,0.047360,1.000000e-09,423.9818,9.699662e+05,344800,66448,0,3147,0.047360,0.126489,0.026840,0.153329,5219
13,0.375,0.043192,1.000000e-09,436.0253,9.431746e+05,344800,66448,0,2871,0.043207,0.126489,0.029671,0.156159,5770
14,0.400,0.039143,1.000000e-09,472.7508,8.699044e+05,344800,66448,0,2602,0.039158,0.126489,0.032898,0.159387,6397
15,0.425,0.035592,1.000000e-09,487.9901,8.427384e+05,344800,66448,0,2366,0.035607,0.126489,0.036064,0.162553,7013
16,0.450,0.032281,1.000000e-09,382.8785,1.074095e+06,344800,66448,0,2146,0.032296,0.126489,0.039490,0.165978,7680
17,0.475,0.029422,1.000000e-09,323.8719,1.269786e+06,344800,66448,0,1956,0.029437,0.126489,0.043404,0.169892,8440
18,0.500,0.026773,1.000000e-09,300.7132,1.367575e+06,344800,66448,0,1780,0.026788,0.126489,0.047562,0.174050,9249
19,0.525,0.024290,1.000000e-09,322.2295,1.276258e+06,344800,66448,0,1615,0.024305,0.126489,0.052139,0.178628,10139
20,0.550,0.022484,1.000000e-09,330.6411,1.243790e+06,344800,66448,0,1495,0.022499,0.126489,0.056969,0.183457,11079
21,0.575,0.020738,1.000000e-09,323.2119,1.272379e+06,344800,66448,0,1379,0.020753,0.126489,0.062180,0.188668,12092
22,0.600,0.018797,1.000000e-09,326.6925,1.258823e+06,344800,66448,0,1250,0.018812,0.126489,0.068260,0.194749,13274
23,0.625,0.017186,1.000000e-09,340.2441,1.208685e+06,344800,66448,0,1143,0.017201,0.126489,0.074928,0.201417,14571
24,0.650,0.015817,1.000000e-09,343.3251,1.197838e+06,344800,66448,0,1052,0.015832,0.126489,0.082176,0.208665,15981
25,0.675,0.014327,1.000000e-09,351.6116,1.169609e+06,344800,66448,0,953,0.014342,0.126489,0.090302,0.216790,17561
26,0.700,0.013063,1.000000e-09,394.5197,1.042402e+06,344800,66448,0,869,0.013078,0.126489,0.099335,0.225823,19318
27,0.725,0.011633,1.000000e-09,370.1896,1.110912e+06,344800,66448,0,774,0.011648,0.126489,0.109512,0.236001,21298
28,0.750,0.010715,1.000000e-09,580.3379,7.086354e+05,344800,66448,0,713,0.010730,0.126489,0.121368,0.247857,23604
29,0.775,0.009601,4.023705e-04,603.9647,6.809140e+05,344800,66448,0,667,0.010038,0.126489,0.051224,0.177712,26406
30,0.800,0.008683,1.328050e-03,633.3950,6.492757e+05,344800,66448,0,663,0.009978,0.126489,0.048653,0.175141,29598
31,0.825,0.007540,2.478960e-03,559.2271,7.353864e+05,344800,66448,0,674,0.010143,0.126489,0.049843,0.176332,33479
32,0.850,0.006366,3.657402e-03,568.9323,7.228417e+05,344800,66448,0,651,0.009797,0.126489,0.053040,0.179528,38093
33,0.875,0.005297,4.727669e-03,653.5777,6.292259e+05,344800,66448,0,658,0.009902,0.126489,0.058365,0.184854,43929
34,0.900,0.004289,5.735532e-03,722.7214,5.690270e+05,344800,66448,0,669,0.010068,0.126489,0.066055,0.192544,51580
35,0.925,0.003296,6.726359e-03,674.0675,6.100991e+05,344800,66448,0,671,0.010098,0.126489,0.077301,0.203790,62283
36,0.950,0.002167,7.849903e-03,686.5356,5.990192e+05,344800,66448,0,669,0.010068,0.126489,0.095222,0.221711,79172

In [57]:
best_lbf

{'threshold': 0.85,
 'model_fp_rate': 0.006365880086684325,
 'backup_target_fpr': 0.003657402499053389,
 'time_taken_ms': 568.932299996959,
 'throughput_s': 722841.7159690144,
 'insert_count': 344800.0,
 'negative_queries': 66448.0,
 'false_negative': 0.0,
 'false_positive': 651.0,
 'observed_fpr': 0.009797134601492896,
 'model_memory_mb': 0.12648868560791016,
 'backup_memory_mb': 0.05303955078125,
 'total_memory_mb': 0.17952823638916016,
 'backup_key_count': 38093.0}